### ISSUE TITLE
Gsource repo 

### ISSUE THREAD

**Issue by Greg0580** [mrgsi/repository.gsource#2]
I just want to thank you for your latest Gsource repo .
Thank you for Updating Open Wizard  and Speed tester For kodi 20 .
I have used both on Kodi 19. And  Glade to see them for kodi 20 and above.  They are both working with No problems.  
Thank you for all your time

**Comment by mrgsi** [comment]
Thank you, I really appreciate the feedback.

**Comment by Greg0580** [comment]
You are welcome.
I have tried lots of different Wizard cleaners  and I have found the Open Wizard to be best of them  at keeping kodi  clean, get rid of  errors , and updating Repos and Addons  etc.  After you have used the cleaners in the Addons etc.
And the speed tester is Good to check your  kodi internet  connection speed.
The only thing I would suggest is that you could download them individually.  Like gman/speed tester and gman/Open Wizard  or similar.
Thank you and have a Good day.  And look forward to see what you come up with next 👍.



Sent from my Galaxy



-------- Original message --------
From: G-Man ***@***.***>
Date: 21/04/23 00:58 (GMT+12:00)
To: "mrgsi/repository.gsource" ***@***.***>
Cc: Greg0580 ***@***.***>, Author ***@***.***>
Subject: Re: [mrgsi/repository.gsource] Gsource repo (Issue #2)


Thank you, I really appreciate the feedback.
