### ISSUE TITLE
Open Wizard from Gsource repo

### ISSUE THREAD

**Issue by Greg0580** [mrgsi/repository.gsource#4]
Hello
I have been using Open Wizard 2.0.9.
From the gsource repo.  
When I tried to remove a addon  it just spins then showed a error and to  press the home button on my firestick Max remote and force stop kodi.  It did not completely remove the addon and repo. 
Unfortunately I don't have the details of the error.  
I installed Gui Wizard and it remove the addon
I don't know if just  me course I'm a Firestick Max.  
I just wanted to let you know. 
Thank you for some good repos/Addons. 👍

**Comment by mrgsi** [comment]
I will have a look at it, but I'm not much of a coder. Basically, it's version 2.0.7 that just allows builders to define their builds as being for Kodi 20 and 21. I don't know if I can follow the code well enough to figure out that specific function, but doesn't hurt to look. I've never used that function myself as I'd think it would be better to just click uninstall on the add-on itself.

**Comment by Greg0580** [comment]
Thank you for your reply and will do have a good evening.  👍



Sent from my Galaxy



-------- Original message --------
From: G-Man ***@***.***>
Date: 24/05/23 13:02 (GMT+12:00)
To: "mrgsi/repository.gsource" ***@***.***>
Cc: Greg0580 ***@***.***>, Author ***@***.***>
Subject: Re: [mrgsi/repository.gsource] Open Wizard from Gsource repo (Issue #4)


I will have a look at it, but I'm not much of a coder. Basically, it's version 2.0.7 that just allows builders to define their builds as being for Kodi 20 and 21. I don't know if I can follow the code well enough to figure out that specific function, but doesn't hurt to look. I've never used that function myself as I'd think it would be better to just click uninstall on the add-on itself.
